#! /bin/bash
yum install java -y
wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo 
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key 
yum install jenkins -y
sudo systemctl enable jenkins
sudo systemctl start jenkins
